export const CREATE_EMPLOYEE = "CREATE_TUTORIAL";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_ALL_EMPLOYEES = "DELETE_ALL_EMPLOYEES";
export const IS_LOGGED_MODAL = "IS_LOGGED_MODAL";